/**********************************************************************
 * Extern for saveAs
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/

/*
 * @param {Blob} blob
 * @param {string} name
 * @param {Object=} opt_options
 */
var saveAs = function (blob, name, opt_options) {};


/**********************************************************************
 * End Generated Extern for saveAs
/**********************************************************************/




