/**********************************************************************
 * Extern for jsPDF
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var jsPDF = {
  "API": {
    "acroformPlugin": {
      "acroFormDictionaryRoot": {},
      "fields": {},
      "internal": {},
      "printedOut": {},
      "xForms": {}
    },
    "addField": function () {},
    "addHTML": function () {},
    "addImage": function () {},
    "addJS": function () {},
    "addSVG": function () {},
    "annotationPlugin": {
      "annotations": {},
      "f2": function () {},
      "notEmpty": function () {}
    },
    "arrayBufferToBase64": function () {},
    "arrayBufferToBinaryString": function () {},
    "arrayMax": function () {},
    "autoPrint": function () {},
    "binaryStringToUint8Array": function () {},
    "calculateLineHeight": function () {},
    "canvas": {
      "getContext": function () {},
      "style": {}
    },
    "cell": function () {},
    "cellAddPage": function () {},
    "cellInitialize": function () {},
    "color_spaces": {
      "CAL_GREY": {},
      "CAL_RGB": {},
      "DEVICE_CMYK": {},
      "DEVICE_GRAY": {},
      "DEVICE_N": {},
      "DEVICE_RGB": {},
      "ICC_BASED": {},
      "INDEXED": {},
      "LAB": {},
      "PATTERN": {},
      "SEPERATION": {}
    },
    "context2d": {
      "_getBaseline": function () {},
      "_gotoPage": function () {},
      "_page": function () {},
      "_wrapX": function () {},
      "_wrapY": function () {},
      "arc": function () {},
      "beginPath": function () {},
      "bezierCurveTo": function () {},
      "clearRect": function () {},
      "clip": function () {},
      "closePath": function () {},
      "drawImage": function () {},
      "f2": function () {},
      "fill": function () {},
      "fillRect": function () {},
      "fillText": function () {},
      "getTextBaseline": function () {},
      "internal": {
        "arc": function () {},
        "createArc": function () {},
        "createSmallArc": function () {},
        "rxRgb": {},
        "rxRgba": {}
      },
      "lastBreak": {},
      "lineTo": function () {},
      "measureText": function () {},
      "moveTo": function () {},
      "pageBreaks": {},
      "pageWrapX": {},
      "pageWrapXEnabled": {},
      "pageWrapY": {},
      "pageWrapYEnabled": {},
      "quadraticCurveTo": function () {},
      "restore": function () {},
      "save": function () {},
      "setFillStyle": function () {},
      "setFont": function () {},
      "setLineCap": function () {},
      "setLineJoin": function () {},
      "setLineWidth": function () {},
      "setStrokeStyle": function () {},
      "setTextBaseline": function () {},
      "stroke": function () {},
      "strokeRect": function () {},
      "strokeText": function () {},
      "translate": function () {}
    },
    "createAnnotation": function () {},
    "createImageInfo": function () {},
    "decode": {
      "ASCII85_DECODE": {},
      "ASCII_HEX_DECODE": {},
      "CCITT_FAX_DECODE": {},
      "DCT_DECODE": {},
      "FLATE_DECODE": {},
      "JBIG2_DECODE": {},
      "JPX_DECODE": {},
      "LZW_DECODE": {},
      "RUN_LENGTH_DECODE": {}
    },
    "events": {},
    "extractInfoFromBase64DataURI": function () {},
    "fromHTML": function () {},
    "getCharWidthsArray": function () {},
    "getLineHeight": function () {},
    "getStringUnitWidth": function () {},
    "getTextDimensions": function () {},
    "getTextWidth": function () {},
    "image_compression": {
      "FAST": {},
      "MEDIUM": {},
      "NONE": {},
      "SLOW": {}
    },
    "isArrayBuffer": function () {},
    "isArrayBufferView": function () {},
    "isString": function () {},
    "link": function () {},
    "printHeaderRow": function () {},
    "processJPEG": function () {},
    "processJPG": function () {},
    "processPNG": function () {},
    "putTotalPages": function () {},
    "sHashCode": function () {},
    "setHeaderFunction": function () {},
    "setTableHeaderRow": function () {},
    "splitTextToSize": function () {},
    "supportsArrayBuffer": function () {},
    "table": function () {},
    "textWithLink": function () {}
  },
  "adler32cs": {
    "Adler32": {
      "from": function () {},
      "fromBuffer": function () {},
      "fromUtf8": function () {}
    },
    "from": function () {},
    "fromBuffer": function () {},
    "fromUtf8": function () {}
  },
  "version": {}
};
jsPDF.adler32cs.Adler32.prototype = {
  "clone": function () {},
  "constructor": function () {},
  "update": function () {},
  "updateBuffer": function () {},
  "updateUtf8": function () {}
};
jsPDF.adler32cs.Adler32.from.prototype = {
  "clone": function () {},
  "constructor": function () {},
  "update": function () {},
  "updateBuffer": function () {},
  "updateUtf8": function () {}
};
jsPDF.adler32cs.Adler32.fromBuffer.prototype = {
  "clone": function () {},
  "constructor": function () {},
  "update": function () {},
  "updateBuffer": function () {},
  "updateUtf8": function () {}
};
jsPDF.adler32cs.Adler32.fromUtf8.prototype = {
  "clone": function () {},
  "constructor": function () {},
  "update": function () {},
  "updateBuffer": function () {},
  "updateUtf8": function () {}
};
/**********************************************************************
 * End Generated Extern for jsPDF
/**********************************************************************/